export const RESET_ERROR_MESSAGE = 'RESET_ERROR_MESSAGE'

export const CONTACT_DETAILS_REQUEST = 'CONTACT_DETAILS_REQUEST'
export const CONTACT_DETAILS_SUCCESS = 'CONTACT_DETAILS_SUCCESS'
export const CONTACT_DETAILS_FAILURE = 'CONTACT_DETAILS_FAILURE'

export const TICKETS_REQUEST = 'TICKETS_REQUEST'
export const TICKETS_SUCCESS = 'TICKETS_SUCCESS'
export const TICKETS_FAILURE = 'TICKETS_FAILURE'

export const PROPERTIES_REQUEST = 'PROPERTIES_REQUEST'
export const PROPERTIES_SUCCESS = 'PROPERTIES_SUCCESS'
export const PROPERTIES_FAILURE = 'PROPERTIES_FAILURE'
